import { describe, it, expect } from 'vitest';
import { join } from 'node:path';
import { generateHtmlReport } from '../../src/formatters/html-report.js';

const FIXTURES_DIR = join(process.cwd(), 'tests', 'fixtures', 'sample-session');

describe('generateHtmlReport', () => {
  it('should produce valid HTML containing session data', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('</html>');
    expect(html).toContain('Exploratory Testing Report');
    expect(html).toContain('Example App');
  });

  it('should include bug cards for all bugs', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    expect(html).toContain('BUG-001');
    expect(html).toContain('BUG-002');
    expect(html).toContain('BUG-003');
  });

  it('should display bug cards in severity order (critical first)', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    const bug002Pos = html.indexOf('BUG-002'); // critical
    const bug001Pos = html.indexOf('BUG-001'); // high
    const bug003Pos = html.indexOf('BUG-003'); // low

    // Critical (BUG-002) should appear before High (BUG-001)
    expect(bug002Pos).toBeLessThan(bug001Pos);
    // High (BUG-001) should appear before Low (BUG-003)
    expect(bug001Pos).toBeLessThan(bug003Pos);
  });

  it('should apply correct severity colors via CSS classes', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    // Critical bug should have critical class
    expect(html).toContain('severity-critical');
    // High bug should have high class
    expect(html).toContain('severity-high');
    // Low bug should have low class
    expect(html).toContain('severity-low');
  });

  it('should include severity color definitions in CSS', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    expect(html).toContain('#ff4757'); // critical
    expect(html).toContain('#ffa502'); // high
    expect(html).toContain('#ffd32a'); // medium
    expect(html).toContain('#3498db'); // low
  });

  it('should include severity badges', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    expect(html).toContain('badge-critical');
    expect(html).toContain('badge-high');
    expect(html).toContain('badge-low');
  });

  it('should include the footer attribution', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    expect(html).toContain('Generated by Qualiow Exploratory Testing');
  });

  it('should include stat cards with correct counts', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    // Total: 3, Critical: 1, High: 1, Medium: 0, Low: 1
    expect(html).toContain('stat-total');
    expect(html).toContain('stat-critical');
    expect(html).toContain('stat-high');
    expect(html).toContain('stat-low');
  });

  it('should contain dark mode background color', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    expect(html).toContain('#0a0f1a');
  });

  it('should include print-friendly styles', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    expect(html).toContain('@media print');
  });

  it('should include responsive styles', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    expect(html).toContain('@media (max-width: 600px)');
  });

  it('should include recommendations from session report', async () => {
    const html = await generateHtmlReport(FIXTURES_DIR);

    expect(html).toContain('Recommendations');
    expect(html).toContain('XSS vulnerability');
  });
});
